services:
  api:
    image: insurancepolicy
    container_name: insurancepolicy-api
    build:
      context: .
      dockerfile: InsurancePolicy/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - insurancepolicy-network

  postgres:
    image: postgres
    container_name: insurancepolicy-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-insured}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iP@2025}
      POSTGRES_DB: ${POSTGRES_DB:-insurancedb}
    volumes:
      - insurancepolicy-pgdata:/var/lib/postgresql/data
    networks:
      - insurancepolicy-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: insurancepolicy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@joshuaondieki.com
      PGADMIN_DEFAULT_PASSWORD: a@dmIn3..
    ports:
      - "8888:80"
    depends_on:
      - postgres
    networks:
      - insurancepolicy-network

volumes:
  insurancepolicy-pgdata:

networks:
  insurancepolicy-network:
